"""Added column in the workout log

Revision ID: b361722ae2cf
Revises: 8272593a0fe0
Create Date: 2024-02-15 14:24:18.011923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b361722ae2cf'
down_revision = '8272593a0fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_type_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_log', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('workout_type_image')

    # ### end Alembic commands ###
